### ISSUE TITLE
Get all Invitations from Cooperation as cooperation admin

### ISSUE THREAD

**Issue by EkaterinaYatsyna** [ita-social-projects/Home#361]
### Description:

- Necessary to add an endpoint to receive all Invitations by the cooperation
- only for such a role as "cooperation admin"
- write tests

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/361?planning-poker) with ZenHub @EkaterinaYatsyna @Sorex1992 @varhanovdm @VladyslavZhigir

**Comment by kh0ma** [comment]
A new requirement from UI team was highlighted. We also need to return information on the associated apartment for the particular apartment invitation. Please see https://app.zenhub.com/workspaces/home-ui-6151e14f1b3ecb001052d692/issues/ita-social-projects/home-ui/121

From my perspective, it can be done via embedding apartment to invitation with type apartment:
```
GET /invitations?type=apartment
[{
  "type": "apartment"
  "id": "1",
  "apartment": {
    "id": "1",
....
  }
...
}]
```

Please also do not forget to add a query parameter to filter invitations by type in order to filter only apartment invitations.

CC: @MrScors
